import csv

# (phrase_base, preposition, translations)
PHRASES = [
    ("a dime a dozen", "", "Пруд пруди"),
    ("age like wine", "", "Становиться лучше с годами"),
    ("at breaking point", "", "На грани срыва"),
    ("at the expense of", "of", "За счет чего-либо"),
    ("be mindful of", "of", "Помнить о|Принимать во внимание"),
    ("be on the lookout for", "for", "Быть в поиске|Высматривать"),
    ("breathe new life into", "into", "Вдохнуть новую жизнь в"),
    ("burn it down", "", "Начать все с чистого листа"),
    ("call it quits", "", "Бросить что-то делать|Прекратить"),
    ("century-long bond", "", "Облигация сроком на столетие"),
    ("collecting dust", "", "Пылиться без дела"),
    ("cost an arm and a leg", "", "Стоить целое состояние"),
    ("daily driver", "", "Основное устройство"),
    ("denominated in sterling", "in", "Номинированный в фунтах стерлингов"),
    ("developed with feedback in mind", "", "Разработанный с учетом отзывов"),
    ("do or die", "", "Пан или пропал"),
    ("drive home", "", "Донести мысль|Убедить"),
    ("eclipsed by", "by", "Затменный|Оставленный позади"),
    ("embrace", "", "Охватывать|Принимать идею или культуру"),
    ("fall into a trap", "into", "Попасть в ловушку"),
    ("find one's footing", "", "Нащупать почву|Освоиться"),
    ("foot the bill", "", "Оплачивать счета"),
    ("gain a foothold", "", "Закрепиться|Обосноваться"),
    ("galaxy brain", "", "Мегамозг иронично"),
    ("go bust", "", "Обанкротиться"),
    ("in light of", "of", "В свете чего-либо"),
    ("in the market for", "for", "Заинтересован в покупке"),
    ("in the spotlight", "", "В центре внимания"),
    ("in the works", "", "В процессе разработки"),
    ("in touch with", "with", "В контакте с|На связи с"),
    ("jack-of-all-trades", "", "Мастер на все руки"),
    ("jump ship", "", "Перейти к конкуренту|Дезертировать"),
    ("lay the foundation of", "of", "Закладывать основу"),
    ("lay the groundwork for", "for", "Закладывать основу для"),
    ("make the jump", "", "Совершить переход"),
    ("on the cards", "", "Вероятный|Ожидаемый"),
    ("pump the brakes", "", "Притормозить"),
    ("punch above its weight", "", "Добиться большего чем ожидалось"),
    ("raise the bar", "", "Поднимать планку"),
    ("scattershot approach", "", "Беспорядочный подход|Пальба по площадям"),
    ("step in the right direction", "", "Шаг в правильном направлении"),
    ("stick the landing", "", "Успешно завершить"),
    ("take the lead", "", "Взять на себя инициативу"),
    ("to be announced", "", "Будет объявлено позже"),
    ("under the hood", "", "Внутреннее устройство|Под капотом"),
    ("upside down", "", "Вверх дном"),
    ("wear and tear", "", "Естественный износ"),
    ("worth the effort", "", "Стоящий усилий"),
    ("go back", "", "Возвращаться"),
    ("come back", "", "Возвращаться"),
    ("come up", "", "Появляться|Возникать|Подниматься"),
    ("take off", "", "Снимать с себя|Уходить|Уезжать"),
    ("pull out", "", "Вытаскивать|Вынимать|Отъезжать"),
    ("hold up", "", "Поднимать"),
    ("walk away", "", "Уходить"),
    ("get off", "", "Выходить|Покидать|Уносить"),
    ("come over", "", "Приходить|Подходить|Заезжать"),
    ("go off", "", "Уходить|Уезжать|Убегать"),
    ("run out", "", "Выбегать|Кончаться|Истощаться"),
    ("hold out", "", "Протягивать|Вытягивать"),
    ("a while ago", "", "Некоторое время назад|Раньше"),
    ("where am I change", "", "Где мне пересесть"),
    ("go as far as", "", "Езжайте до|Идите до"),
    ("about time", "", "Наконец-то"),
    ("after a while", "", "Через некоторое время"),
    ("ahead of time", "", "Заранее"),
    ("all along", "", "Всё время"),
    ("all day long", "", "С утра до вечера"),
    ("all the while", "", "Всё это время"),
    ("any day now", "", "Когда угодно"),
    ("at a moment's notice", "", "В любой момент"),
    ("at a time", "", "В то время когда"),
    ("at all times", "", "Всё время без перерыва"),
    ("at last", "", "Наконец"),
    ("at one time", "", "Одно время"),
    ("at that point", "", "В этот момент"),
    ("at the point of", "of", "В момент чего-либо"),
    ("at the same time", "", "В то же время"),
    ("at the worst possible time", "", "В самое неподходящее время"),
    ("at times", "", "Иногда"),
    ("day after day", "", "День за днём"),
    ("day and night", "", "Днём и ночью"),
    ("day in day out", "", "Целыми днями"),
    ("every now and then", "", "Время от времени|Периодически"),
    ("every so often", "", "Время от времени|Периодически"),
    ("for good", "", "Навсегда"),
    ("for the moment", "", "Что касается настоящего момента"),
    ("from now on", "", "Отныне и впредь"),
    ("from the ground up", "", "С самого начала"),
    ("from this day forward", "", "Отныне и впредь"),
    ("from time to time", "", "Время от времени"),
    ("from way back", "", "С давних пор"),
    ("hard times", "", "Трудные времена"),
    ("have a hard time", "", "Иметь трудности с чем-то"),
    ("have all the time in the world", "", "Иметь уйму времени"),
    ("high time", "", "Самое время"),
    ("his days are numbered", "", "Его дни сочтены"),
    ("hurry up", "", "Поторапливайся"),
    ("in his day", "", "В своё время"),
    ("in no time", "", "Мигом"),
    ("in old days", "", "В былые времена"),
    ("in the meantime", "", "Тем временем"),
    ("in time", "", "Вовремя|Как раз вовремя"),
    ("it can wait", "", "Это может подождать"),
    ("it's a matter of time", "", "Вопрос времени"),
    ("just about", "", "Почти уже"),
    ("just now", "", "Как раз сейчас"),
    ("long ago", "", "Давно"),
    ("make haste", "", "Спешить"),
    ("make time", "", "Спешить"),
    ("more often than not", "", "Чаще всего"),
    ("no longer", "", "Больше нет"),
    ("on and off", "", "Время от времени|С перерывами"),
    ("on and on", "", "Непрерывно|Снова и снова"),
    ("on the spot", "", "На месте|Без промедления"),
    ("on time", "", "Точно в назначенное время"),
    ("once and for all", "", "Раз и навсегда"),
    ("once in a while", "", "Изредка"),
    ("out of date", "", "Устаревший"),
    ("play for time", "", "Тянуть время"),
    ("right away", "", "Прямо сейчас"),
    ("round the clock", "", "Круглые сутки"),
    ("run out of time", "", "Не успевать"),
    ("so far", "", "До сих пор"),
    ("sooner or later", "", "Рано или поздно"),
    ("speak too soon", "", "Говорить преждевременно"),
    ("take time", "", "Занимать время"),
    ("the whole year round", "", "Круглый год"),
    ("there is no hurry", "", "Спешить некуда"),
    ("till the end of time", "", "До скончания веков"),
    ("time after time", "", "Раз за разом|Регулярно"),
    ("time is up", "", "Время вышло"),
    ("time out", "", "Перерыв"),
    ("time will tell", "", "Время покажет"),
    ("time's getting short", "", "У нас мало времени"),
    ("wait and see", "", "Поживём увидим"),
    ("to meet a colleague from abroad", "", "Встречать коллегу из-за границы"),
    ("to answer questions for an application form", "", "Отвечать на вопросы анкеты"),
    ("to chat about the news", "", "Болтать о новостях"),
    ("to get to know each other during a break", "", "Познакомиться во время перерыва"),
    ("to spend a lot of time", "", "Провести много времени"),
    ("to be quite good at", "at", "Быть в чем-либо успешным"),
    ("to be really into", "into", "Быть вовлеченным в"),
    ("to be interested in", "in", "Интересоваться"),
    ("to hang out with friends", "", "Зависать с друзьями"),
    ("to text your friends", "", "Писать смс друзьям"),
    ("to be physically active", "", "Быть физически активным"),
    ("to chat on the phone", "", "Болтать по телефону"),
    ("to use the Internet", "", "Пользоваться интернетом"),
    ("to work longer hours", "", "Работать долгими часами"),
    ("to work fulltime", "", "Иметь полный рабочий график"),
    ("to do the main share of the housework", "", "Выполнять основную часть работы по дому"),
    ("to have a full-time job", "", "Иметь работу с полным рабочим графиком"),
    ("to socialize", "", "Общаться"),
    ("to be keen on sport", "on", "Увлекаться спортом"),
    ("to take part in sport", "in", "Принимать участие в спорте"),
    ("to waste a lot of time", "", "Зря тратить много времени"),
    ("to be stressed out and exhausted", "", "Находиться в состоянии стресса и истощения"),
    ("to do sport", "", "Заниматься спортом"),
    ("to send e-mails to friends", "", "Слать имейлы друзьям"),
    ("to improve English", "", "Улучшать английский"),
    ("to look after children and to do the housework", "", "Смотреть за детьми и делать домработу"),
    ("to be terrible at housework", "at", "Быть никудышным для домашней работы"),
    ("to move to a new office", "to", "Переезжать в новый офис"),
    ("to be bored with smth", "with", "Тяготиться чем-либо"),
    ("to look for smth", "for", "Искать что-либо"),
    ("to go and live abroad", "", "Выезжать и жить за границей"),
    ("to set up a travel business", "", "Основывать турбизнес"),
    ("to play the guitar the violin", "", "Играть на гитаре и скрипке"),
    ("to have got a stomachache", "", "Иметь желудочные колики"),
    ("to have got a cold", "", "Подхватить насморк"),
    ("to comfort smb", "", "Успокаивать кого-либо"),
    ("to share smth", "", "Делиться чем-либо"),
    ("to be generous", "", "Быть великодушным"),
    ("to get in touch with", "with", "Связаться с"),
    ("to go shopping", "", "Ходить за покупками"),
    ("to load up a car", "", "Загрузить машину"),
    ("to drop smth", "", "Уронить что-либо"),
    ("to start to panic", "", "Начать паниковать"),
    ("to knock at the door", "at", "Постучать в дверь"),
    ("to be grateful", "", "Быть благодарным"),
    ("to own a gun", "", "Иметь пистолет"),
    ("to have a motive for killing", "for", "Иметь мотив для убийства"),
    ("to try an experiment", "", "Поставить следственный эксперимент"),
    ("to believe in telepathy", "in", "Верить в телепатию"),
    ("to set a good example", "", "Подавать хороший пример"),
    ("to give up smoking", "", "Бросать курение"),
    ("to lose a lot of weight", "", "Терять много веса"),
    ("to suffer from stress", "from", "Страдать от стресса"),
    ("to eat a more varied diet", "", "Сидеть на более разнообразной диете"),
    ("to have sense of humour", "", "Иметь чувство юмора"),
    ("to have a bad back", "", "Иметь боли в пояснице"),
    ("to have a walk", "", "Прогуляться"),
    ("to get on very well", "", "Отлично ладить"),
    ("to pass a driving test", "", "Сдать тест на вождение"),
    ("to be wrong about someone", "about", "Ошибиться на чей-то счет"),
    ("to go out on someone's first date", "", "Выйти в свет при первом свидании"),
    ("to tidy the house", "", "Убирать дом"),
    ("to give smb a lift", "", "Подобрать кого-либо"),
    ("to fall off a bike", "off", "Падать с велосипеда"),
    ("to drive past smb", "", "Проезжать мимо кого-либо"),
    ("to pay attention to smth", "to", "Обратить внимание на что-либо"),
    ("to be frightened of smb", "of", "Быть напуганным кем-либо"),
    ("to get into trouble", "into", "Попасть в передрягу"),
    ("to bully smb", "", "Задирать кого-либо"),
    ("to win a prize", "", "Выигрывать приз"),
    ("to get angry with smb", "with", "Злиться на кого-либо"),
    ("to stand in line", "in", "Стоять в шеренге"),
    ("to bump into smb", "into", "Врезаться в кого-либо|Столкнуться"),
    ("to call smb names", "", "Обзывать кого-либо"),
    ("to threaten to beat smb", "", "Грозиться побить кого-либо"),
    ("to be terrified", "", "Быть запуганным"),
    ("to arrest smb", "", "Арестовывать кого-либо"),
    ("to dare go out to the beach", "", "Осмелиться пойти на пляж"),
    ("to be lost", "", "Потеряться"),
    ("to appear on stage", "on", "Появиться на сцене"),
    ("to look around", "", "Осмотреться"),
    ("to take a wrong turn", "", "Повернуть в неверном направлении"),
    ("to ask for directions", "for", "Спросить о направлении"),
    ("to manage to do smth", "", "Успешно что-либо делать"),
    ("to find smth boring", "", "Считать что-либо скучным"),
    ("to improve memory", "", "Улучшать память"),
    ("to take responsibility", "", "Брать ответственность"),
    ("to make an effort", "", "Делать усилие"),
    ("to remember smth effortlessly", "", "Помнить что-либо без усилий"),
    ("to focus on facts consciously", "on", "Сконцентрироваться сознательно на фактах"),
    ("to create visual associations", "", "Создавать визуальные ассоциации"),
    ("to organize ideas in a logical way", "", "Организовывать идеи логически"),
    ("to keep one's brain fit", "", "Поддерживать умственную форму"),
    ("to increase heart rate", "", "Повышать сердцебиение"),
    ("to reduce stress", "", "Уменьшать стресс"),
    ("to concentrate on smth", "on", "Концентрироваться на чем-либо"),
    ("to lose memory", "", "Терять память"),
    ("to learn by heart", "by", "Учить на память"),
    ("to lose a large amount of money", "", "Терять большую сумму денег"),
]

import csv
rows = [["word", "part_of_speech", "preposition", "translations"]]
for word, prep, trans in PHRASES:
    rows.append([word, "phrase", prep, trans])

with open("resource/import/vocabulary_phrase.csv", "w", newline="", encoding="utf-8") as f:
    csv.writer(f).writerows(rows)

print(f"Written {len(rows)-1} phrase rows")
