package db

var irregularVerbs = []string{
	"Идти;Go - Went - Gone",
	"Петь;Sing - Sang - Sung",
	"Есть;Eat - Ate - Eaten",
	"Спать;Sleep - Slept - Slept",
	"Говорить;Speak - Spoke - Spoken",
	"Брать;Take - Took - Taken",
	"Бежать;Run - Ran - Run",
	"Читать;Read - Read - Read",
	"Писать;Write - Wrote - Written",
	"Плавать;Swim - Swam - Swum",
	"Лететь;Fly - Flew - Flown",
	"Водить;Drive - Drove - Driven",
	"Ломать;Break - Broke - Broken",
	"Строить;Build - Built - Built",
	"Выбирать;Choose - Chose - Chosen",
	"Забывать;Forget - Forgot - Forgotten",
	"Встречать;Meet - Met - Met",
	"Думать;Think - Thought - Thought",
	"Учить;Teach - Taught - Taught",
	"Видеть;See - Saw - Seen",
	"Пить;Drink - Drank - Drunk",
	"Иметь;Have - Had - Had",
	"Делать;Do - Did - Done",
	"Говорить;Say - Said - Said",
	"Покупать;Buy - Bought - Bought",
	"Ломать;Break - Broke - Broken",
	"Начинать;Begin - Began - Begun",
	"Выбирать;Choose - Chose - Chosen",
	"Падать;Fall - Fell - Fallen",
	"Знать;Know - Knew - Known",
	"Говорить;Speak - Spoke - Spoken",
	"Спать;Sleep - Slept - Slept",
	"Находить;Find - Found - Found",
	"Терять;Lose - Lost - Lost",
	"Выигрывать;Win - Won - Won",
	"Рисовать;Draw - Drew - Drawn",
	"Держать;Hold - Held - Held",
	"Делать;Make - Made - Made",
	"Платить;Pay - Paid - Paid",
	// Add other verbs with the same format
	// ...
}
